config/routes.rb
OngakuRyoho::Application.routes.draw do

  # api
  namespace :api do
    resources :tracks,      only: [:index]
    resources :favourites,  only: [:index, :create, :destroy]
    resources :playlists,   only: [:index, :create, :update, :destroy]

    resources :sources,     only: [:index, :show, :create, :update, :destroy] do
      member do
        get :file_list
        post :update_tracks
        get :s3_signed_url
        get :dropbox_media_url
      end

      collection do
        get :dropbox_authorize_url
      end
    end
  end

  # pages
  get 'about'       => 'pages#about'
  get 'settings'    => 'pages#settings'
  get 'tools'       => 'pages#tools'
  get 'faq'         => 'pages#faq'

  # settings
  put 'settings'    => 'pages#update_settings'

  # sessions/users
  devise_for :users,
    path: "",
    skip: [:sessions, :registrations],
    controllers: {
      passwords: "passwords"
    }

  as :user do
    get     'sign-in'  => 'sessions#new',     as: 'new_user_session'
    post    'sign-in'  => 'sessions#create',  as: 'user_session'
    get     'sign-out' => 'sessions#destroy', as: 'destroy_user_session'

    # registrations
    get   'sign-up' => 'users#new',    as: 'new_user_registration'
    post  'sign-up' => 'users#create', as: 'user_registration'

    # account
    get 'account' => 'users#edit',   as: 'edit_user_registration'
    put 'account' => 'users#update', as: 'update_user_registration'

    # account deletion
    delete 'account' => 'users#destroy'

    # account created page
    get 'account-created'   => 'users#account_created'
  end

  # root
  root :to => 'default#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :settings, :remember_me
  serialize :settings, ActiveRecord::Coders::Hstore


  #
  #  Associations
  #
  has_many :sources, dependent: :destroy

  has_many :favourites, dependent: :destroy
  has_many :playlists, dependent: :destroy


  #
  #  JSON
  #
  def as_json(options={})
    options = { only: [:settings] }
    super(options)
  end

end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  before_filter :redirect_if_logged_in, only: [:new, :create]
  layout 'pages'


  def account_created
    @page_title = "Account created"
  end

protected

  def after_sign_up_path_for(resource)
    "/account-created"
  end


  def after_update_path_for(resource)
    edit_user_registration_path
  end

end

app/views/users/account_created.html.slim
.mod-account-created
  .title Account created!

  p
    | All set to&nbsp;
    a[href="/"]
      | go listen
      span[data-icon="&#9835;"]
    |  to some music

app/views/users/edit.html.slim
p.a-word-of-advice
  | Here you can choose a new e-mail address and/or password.


= form_for(resource, as: resource_name, url: update_user_registration_path, html: { method: :put }) do |f|
  .fields
    .text
      = f.text_field :email, autofocus: true, placeholder: "ongaku@ryoho.com"

    .text
      = f.password_field :current_password, autocomplete: "off", placeholder: "current password"

    .text
      = f.password_field :password, autocomplete: "off", placeholder: "new password"

    .text
      = f.password_field :password_confirmation, autocomplete: "off", placeholder: "repeat new password"

    .submit
      = f.submit "Edit account"


- if @user.errors.any?
  .flash.error
    i &#59272;
    = @user.errors.full_messages.first


- flash.each do |name, msg|
  - i_content = (name == :error ? "&#59272;" : "&#10003;")
  == content_tag :div,
      content_tag(:i, raw(i_content)) + msg,
      class: "flash #{name}"


.remove-account
  a
    span[data-icon="&#10006;"]
    | Remove account

app/views/users/new.html.slim
p.a-word-of-advice
  | To sign up, we will need an e-mail address and a password.


= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
  .fields
    .text
      = f.email_field :email, autofocus: true, placeholder: "ongaku@ryoho.com"

    .text
      = f.password_field :password, autocomplete: "off", placeholder: "password"

    .text
      = f.password_field :password_confirmation, autocomplete: "off", placeholder: "repeat password"

    .submit
      = f.submit "Create account"


- if @user.errors.any?
  .flash.error
    i &#59272;
    = @user.errors.full_messages.first

- elsif @user_capacity_error
  .flash.error
    i &#128101;
    = @user_capacity_error