config/routes.rb
OngakuRyoho::Application.routes.draw do

  # api
  namespace :api do
    resources :tracks,      only: [:index]
    resources :favourites,  only: [:index, :create, :destroy]
    resources :playlists,   only: [:index, :create, :update, :destroy]

    resources :sources,     only: [:index, :show, :create, :update, :destroy] do
      member do
        get :file_list
        post :update_tracks
        get :s3_signed_url
        get :dropbox_media_url
      end

      collection do
        get :dropbox_authorize_url
      end
    end
  end

  # pages
  get 'about'       => 'pages#about'
  get 'settings'    => 'pages#settings'
  get 'tools'       => 'pages#tools'
  get 'faq'         => 'pages#faq'

  # settings
  put 'settings'    => 'pages#update_settings'

  # sessions/users
  devise_for :users,
    path: "",
    skip: [:sessions, :registrations],
    controllers: {
      passwords: "passwords"
    }

  as :user do
    get     'sign-in'  => 'sessions#new',     as: 'new_user_session'
    post    'sign-in'  => 'sessions#create',  as: 'user_session'
    get     'sign-out' => 'sessions#destroy', as: 'destroy_user_session'

    # registrations
    get   'sign-up' => 'users#new',    as: 'new_user_registration'
    post  'sign-up' => 'users#create', as: 'user_registration'

    # account
    get 'account' => 'users#edit',   as: 'edit_user_registration'
    put 'account' => 'users#update', as: 'update_user_registration'

    # account deletion
    delete 'account' => 'users#destroy'

    # account created page
    get 'account-created'   => 'users#account_created'
  end

  # root
  root :to => 'default#index'

end

app/views/pages/about.html.slim
h1 Ongaku Ryoho



.introduction.with-a-border
  .wrapper
    p
      | <span class="colored">Ongaku Ryoho</span>
        is a web based <strong>music player</strong> that connects to different sources that are defined
        by you. Combine music libraries, centralize your favourites
        and browse easily through your collection. That, plus a beautiful environment.
    p.subtext
      | The name comes from the japanese words 'ongaku ryouhou', which means 'music therapy'



.with-a-border
  .wrapper.content
    .left
      h2: span Supported sources
      ul
        li Dropbox
        li Amazon S3 bucket
        li Ongaku Ryoho Server (<a href="http://rubygems.org/gems/ongaku_ryoho_server">rubygem</a>)

      p
        | Suggestions are welcome (<a href="http://twitter.com/icidasset">@icidasset</a>).

    .right
      h2: span Supported browsers/filetypes
      p
        | On the desktop: Chrome, Firefox (v25), Safari (7+) and Opera (17+).
          Other platforms that I tested: iOS 7 Mobile Safari and Chrome on iOS 6+.
          The files you can play depend on the browser.
          Chrome (v30) supports: mp3, m4a, mp4, wav, ogg, webm.
          For other browsers, see this <a href="http://docs.webplatform.org/wiki/html/elements/audio#Compatibility">compatibility</a> table.



.with-a-border
  .wrapper.content
    img.screenshot[src="/assets/screenshot.png"]

app/views/pages/settings.html.slim
p.a-word-of-advice
  | Application settings

- user = current_user
= form_for user, url: settings_path, method: :put, html: { class: "settings-form" } do |f|
  = f.fields_for :settings do |s|
    = settings_checkbox(s, user, :alternative_knob)
    = s.label :alternative_knob do
      | Use alternative knob-control movement

    br

    = settings_checkbox(s, user, :disable_visualizations)
    = s.label :disable_visualizations do
      | Disable visualizations (e.g. for slow computers,
      |  <span style="font-weight:500;">always disabled on mobile/tablet devices and Safari</span>)

    br

    = settings_checkbox(s, user, :hide_playlist_menu)
    = s.label :hide_playlist_menu do
      | Hide playlist menu when playlist is chosen/clicked

    br
    br

    - tpp_default = 500
    - tpp = user.settings["tracks_per_page"] || tpp_default
    - tpp = tpp_default if tpp == ""

    = s.label :tracks_per_page, "Tracks per page: "
    = text_field_tag "user[settings][tracks_per_page]", tpp
    p
      small
        em note:
        |  It's best to keep this number below 1000

    br

    = s.label :theme, "Color theme: "
    = select_tag "user[settings][theme]", options_for_select(theme_names, user.settings["theme"] || "blue-silver")

  br
  br

  = f.submit "Save settings", class: "with-margin-top"


- flash.each do |name, msg|
  - i_content = (name == :error ? "&#59272;" : "&#10003;")
  == content_tag :div,
      content_tag(:i, raw(i_content)) + msg,
      class: "flash #{name}"